import { CardPeriod } from '../types';

export const CARD_DATA: CardPeriod[] = [
  {
    period: '第2期',
    cards: [
      { id: 'TB-34', name: 'サウザンド・アイズ・サクリファイス' },
      { id: 'SM-00', name: '仮面魔獣マスクド・ヘルレイザー' },
      { id: 'SM-51', name: '青眼の白龍' },
      { id: 'LN-14', name: 'ダーク・ネクロフィア' },
      { id: 'LN-53', name: 'ブラック・マジシャン' },
      { id: 'SC-51', name: 'デーモンの召喚' },
      { id: 'MA-52', name: 'ブラック・デーモンズ・ドラゴン' },
      { id: 'PH-00', name: '不死王リッチー' },
      { id: 'PH-52', name: '暗黒騎士ガイア' },
      { id: 'BC-34', name: 'ヂェミナイ・エルフ' },
    ],
  },
  {
    period: '第3期',
    cards: [
      { id: '301-051', name: '溶岩魔人ラヴァ・ゴーレム' },
      { id: '301-052', name: 'バイサー・ショック' },
      { id: '301-056', name: '真紅眼の黒竜' },
      { id: '302-051', name: 'ＸＹ－ドラゴン・キャノン' },
      { id: '302-052', name: 'ＸＹＺ－ドラゴン・キャノン' },
      { id: '302-055', name: 'リボルバー・ドラゴン' },
      { id: '303-051', name: '超魔導剣士－ブラック・パラディン' },
      { id: '303-054', name: 'バスター・ブレイダー' },
      { id: '304-051', name: 'カイザー・グライダー' },
      { id: '304-054', name: 'カオス・ソルジャー' },
      { id: '305-019', name: 'ジェノサイドキングデーモン' },
      { id: '305-053', name: '暗黒魔族ギルファー・デーモン' },
      { id: '306-025', name: 'カオスソルジャー -開闢の使者-' },
      { id: '306-057', name: 'マジシャン・オブ・ブラックカオス' },
      { id: '307-010', name: '混沌の黒魔術師' },
      { id: '307-057', name: '封印されしエクゾディア' },
      { id: '308-034', name: '大天使ゼラート' },
      { id: '308-057', name: '人造人間-サイコ・ショッカー' },
      { id: '309-007', name: 'スピリッツ・オブ・ファラオ' },
      { id: '309-057', name: '竜騎士ガイア' },
      { id: 'DL1-000', name: '黒衣の大賢者' },
      { id: 'DL1-136', name: 'ビッグ・シールド・ガードナー' },
      { id: 'DL2-000', name: '処刑人-マキュラ' },
      { id: 'DL2-136', name: 'エクスチェンジ' },
      { id: 'DL3-136', name: 'ブレイドナイト' },
      { id: 'DL4-136', name: 'インセクト女王' },
      { id: 'DL5-136', name: '究極完全態・グレート・モス' },
      { id: 'SDX-JP001', name: '青眼の究極竜' },
      { id: 'BPT-J02', name: '混沌帝龍 －終焉の使者－' },
    ],
  },
  {
    period: '第4期',
    cards: [
      { id: 'SOD-JP007', name: 'ホルスの黒炎竜 LV6' },
      { id: 'SOD-JP008', name: 'ホルスの黒炎竜 LV8' },
      { id: 'SOD-JP012', name: 'ミスティック・ソードマン LV4' },
      { id: 'SOD-JP015', name: 'アームド・ドラゴン LV7' },
      { id: 'SOD-JP022', name: '氷帝メビウス' },
      { id: 'SOD-JP033', name: '月の女戦士' },
      { id: 'SOD-JP042', name: '黒炎弾' },
      { id: 'SOD-JP043', name: 'エクトプラズマー' },
      { id: 'SOD-JP055', name: 'グリード' },
      { id: 'SOD-JP057', name: '無効' },
      { id: 'SOD-JP060', name: 'ホーリーライフバリアー' },
      { id: 'RDS-JP005', name: '創生神' },
      { id: 'RDS-JP008', name: 'ミスティック・ソードマン LV6' },
      { id: 'RDS-JP009', name: 'サイレント・ソードマン LV3' },
      { id: 'RDS-JP012', name: 'パーフェクト機械王' },
      { id: 'RDS-JP021', name: '炎帝テスタロス' },
      { id: 'RDS-JP030', name: '巨大戦艦 ビッグ・コア' },
      { id: 'RDS-JP039', name: 'トライアングル・X・スパーク' },
      { id: 'RDS-JP045', name: '死者転生' },
      { id: 'RDS-JP049', name: '断頭台の惨劇' },
      { id: 'RDS-JP050', name: '天罰' },
      { id: 'RDS-JP057', name: 'ピケルの魔法陣' },
      { id: 'FET-JP005', name: 'ネフティスの鳳凰神' },
      { id: 'FET-JP008', name: 'サイレント・ソードマン LV5' },
      { id: 'FET-JP009', name: '地帝グランマーグ' },
      { id: 'FET-JP014', name: '百獣王 ベヒーモス' },
      { id: 'FET-JP020', name: 'ブラッド・マジシャンー煉獄の魔術師ー' },
      { id: 'FET-JP022', name: '剣聖ーネイキッド・ギア・フリード' },
      { id: 'FET-JP035', name: 'ガトリング・ドラゴン' },
      { id: 'FET-JP036', name: '竜魔人 キングドラグーン' },
      { id: 'FET-JP037', name: '鳳凰神の羽根' },
      { id: 'FET-JP040', name: 'ライトニング・ボルテックス' },
      { id: 'FET-JP058', name: '魔のデッキ破壊ウイルス' },
      { id: 'TLM-JP005', name: 'ハネクリボー' },
      { id: 'TLM-JP006', name: '古代の機械巨人' },
      { id: 'TLM-JP010', name: 'アルティメット・インセクト LV7' },
      { id: 'TLM-JP012', name: 'ヒエラコスフィンクス' },
      { id: 'TLM-JP015', name: 'メガロック・ドラゴン' },
      { id: 'TLM-JP020', name: 'マスターモンク' },
      { id: 'TLM-JP033', name: '大邪神 レシェフ' },
      { id: 'TLM-JP035', name: 'E・HERO フレイム・ウィングマン' },
      { id: 'TLM-JP036', name: 'E・HERO サンダー・ジャイアント' },
      { id: 'TLM-JP037', name: '天よりの宝札' },
      { id: 'TLM-JP038', name: '洗脳ーブレインコントロール' },
      { id: 'CRV-JP005', name: 'ハネクリボー LV10' },
      { id: 'CRV-JP010', name: 'ユーフォロイド' },
      { id: 'CRV-JP015', name: 'サイバー・ドラゴン' },
      { id: 'CRV-JP016', name: 'サイバネティック・マジシャン' },
      { id: 'CRV-JP020', name: 'ゴブリンエリート部隊' },
      { id: 'CRV-JP021', name: '巨大戦艦 クリスタル・コア' },
      { id: 'CRV-JP034', name: 'ユーフォロイド・ファイター' },
      { id: 'CRV-JP035', name: 'サイバー・ツイン・ドラゴン' },
      { id: 'CRV-JP036', name: 'サイバー・エンド・ドラゴン' },
      { id: 'CRV-JP037', name: 'パワー・ボンド' },
      { id: 'CRV-JP048', name: '摩天楼 －スカイスクレイパー－' },
      { id: 'EEN-JP007', name: 'E・HERO エッジマン' },
      { id: 'EEN-JP015', name: 'ウォーター・ドラゴン' },
      { id: 'EEN-JP017', name: '巨大戦艦 テトラン' },
      { id: 'EEN-JP024', name: '暗黒界の武神 ゴルド' },
      { id: 'EEN-JP031', name: 'VWXYZードラゴン・カタパルトキャノン' },
      { id: 'EEN-JP032', name: 'サイバー・ブレイダー' },
      { id: 'EEN-JP033', name: 'E・HERO ランパートガンナー' },
      { id: 'EEN-JP034', name: 'E・HERO テンペスター' },
      { id: 'EEN-JP035', name: 'E・HERO ワイルドジャギーマン' },
      { id: 'EEN-JP036', name: 'E・HERO シャイニング・フレア・ウィングマン' },
      { id: 'EEN-JP037', name: '貪欲な壺' },
      { id: 'SOI-JP001', name: '神炎王 ウリア' },
      { id: 'SOI-JP002', name: '降雷王 ハモン' },
      { id: 'SOI-JP003', name: '幻魔王 ラビエル' },
      { id: 'SOI-JP006', name: 'サイバー・バリア・ドラゴン' },
      { id: 'SOI-JP007', name: 'サイバー・レーザー・ドラゴン' },
      { id: 'SOI-JP013', name: '巨大戦艦 カバード・コア' },
      { id: 'SOI-JP033', name: '神竜ーエクセリオン' },
      { id: 'SOI-JP034', name: '破滅の女神ルイン' },
      { id: 'SOI-JP035', name: '終焉の王デミス' },
      { id: 'SOI-JP047', name: '古代の機械城' },
      { id: 'SOI-JP052', name: 'ダメージ・コンデンサー' },
      { id: 'EOJ-JP004', name: 'D・HERO ドレッドガイ' },
      { id: 'EOJ-JP007', name: 'サイバー・プリマ' },
      { id: 'EOJ-JP009', name: 'サイバー・フェニックス' },
      { id: 'EOJ-JP011', name: 'ビクトリー・バイパー XX03' },
      { id: 'EOJ-JP016', name: '光神機ー轟竜' },
      { id: 'EOJ-JP023', name: '裁きを下す者ーボルテニス' },
      { id: 'EOJ-JP031', name: '超電磁稼働ボルテック・ドラゴン' },
      { id: 'EOJ-JP032', name: 'E・HERO フェニックスガイ' },
      { id: 'EOJ-JP033', name: 'E・HERO シャイニング・フェニックスガイ' },
      { id: 'EOJ-JP035', name: 'E・HERO ワイルド・ウィングマン' },
      { id: 'EOJ-JP048', name: '幽獄の時計塔' },
      { id: 'SDX-JP002', name: 'ヴィクトリー・ドラゴン' },
      { id: 'BPT-JP003', name: 'エンド・オブ・アヌビス' },
      { id: 'BPT-JP004', name: 'E・HERO スチーム・ヒーラー' },
      { id: 'W6S-JP001', name: '真紅眼の闇竜' },
      { id: 'W6S-JP002', name: 'ヴァンパイアジェネシス' },
      { id: 'W6S-JP003', name: 'ヘルフレイムエンペラー' },
      { id: 'W6S-JP004', name: '海竜神ーネオダイダロス' },
    ],
  },
  {
    period: '第5期',
    cards: [
      { id: 'POTD-JP003', name: 'N・アクア・ドルフィン' },
      { id: 'POTD-JP004', name: 'N・フレア・スカラベ' },
      { id: 'POTD-JP005', name: 'N・ブラック・パンサー' },
      { id: 'POTD-JP012', name: 'D－HERO ダブルガイ' },
      { id: 'POTD-JP014', name: 'D－HERO ドグマガイ' },
      { id: 'POTD-JP020', name: '究極恐獣' },
      { id: 'POTD-JP031', name: 'E・HERO アクア・ネオス' },
      { id: 'POTD-JP032', name: 'E・HERO フレア・ネオス' },
      { id: 'POTD-JP033', name: 'E・HERO ブラック・ネオス' },
      { id: 'POTD-JP034', name: 'キメラテック・オーバー・ドラゴン' },
      { id: 'POTD-JP036', name: 'スーパービークロイド－ジャンボドリル' },
      { id: 'CDIP-JP001', name: 'サイバー・ダーク・ホーン' },
      { id: 'CDIP-JP002', name: 'サイバー・ダーク・エッジ' },
      { id: 'CDIP-JP003', name: 'サイバー・ダーク・キール' },
      { id: 'CDIP-JP005', name: 'サイバー・エスパー' },
      { id: 'CDIP-JP008', name: '魅惑の女王 LV7' },
      { id: 'CDIP-JP011', name: '漆黒の魔王 LV8' },
      { id: 'CDIP-JP032', name: 'ストーム・シューター' },
      { id: 'CDIP-JP035', name: '鎧黒竜ーサイバー・ダーク・ドラゴン' },
      { id: 'CDIP-JP036', name: 'サイバー・オーガ・２' },
      { id: 'CDIP-JP056', name: 'トロイボム' },
      { id: 'CDIP-JP058', name: 'サイバー・シャドー・ガードナー' },
      { id: 'STON-JP001', name: 'ジェネティック・ワーウルフ' },
      { id: 'STON-JP004', name: 'N・エア・ハミングバード' },
      { id: 'STON-JP013', name: '大将軍 紫炎' },
      { id: 'STON-JP017', name: '暗黒界の魔神 レイン' },
      { id: 'STON-JP034', name: 'E・HERO エアー・ネオス' },
      { id: 'STON-JP035', name: 'E・HERO グラン・ネオス' },
      { id: 'STON-JP036', name: 'E・HERO グロー・ネオス' },
      { id: 'STON-JP038', name: '暗黒界の取引' },
      { id: 'STON-JP046', name: 'カードトレーダー' },
      { id: 'STON-JP048', name: '摩天楼２ーヒーローシティ' },
      { id: 'STON-JP057', name: '正統なる血統' },
      { id: 'FOTB-JP007', name: '宝玉獣 サファイア・ペガサス' },
      { id: 'FOTB-JP008', name: 'ヴォルカニック・デビル' },
      { id: 'FOTB-JP014', name: 'E・HERO キャプテン・ゴールド' },
      { id: 'FOTB-JP021', name: '天魔神 エンライズ' },
      { id: 'FOTB-JP022', name: '天魔神 ノーレラス' },
      { id: 'FOTB-JP023', name: '天魔神 インヴィシル' },
      { id: 'FOTB-JP026', name: '風帝ライザー' },
      { id: 'FOTB-JP031', name: 'ファイアー・ソウル' },
      { id: 'FOTB-JP033', name: 'レア・ヴァリュー' },
      { id: 'FOTB-JP041', name: 'ブレイズ・キャノンートライデント' },
      { id: 'FOTB-JP055', name: '閃光のバリア －シャイニング・フォース－' },
      { id: 'TAEV-JP006', name: '究極宝玉神 レインボー・ドラゴン' },
      { id: 'TAEV-JP013', name: '毒蛇神ヴェノミナーガ' },
      { id: 'TAEV-JP019', name: 'ヘルカイザー・ドラゴン' },
      { id: 'TAEV-JP043', name: 'E・HERO マグマ・ネオス' },
      { id: 'TAEV-JP063', name: '異次元トンネルーミラーゲートー' },
      { id: 'GLAS-JP005', name: '雲魔物－アイ・オブ・ザ・タイフーン' },
      { id: 'GLAS-JP017', name: '剣闘獣アレクサンデル' },
      { id: 'GLAS-JP036', name: 'Ｅ・ＨＥＲＯ カオス・ネオス' },
      { id: 'GLAS-JP038', name: 'Ｅ－ＨＥＲＯ インフェルノ・ウィング' },
      { id: 'GLAS-JP044', name: '剣闘獣ヘラクレイノス' },
      { id: 'PTDN-JP003', name: '究極宝玉神 レインボー・ダーク・ドラゴン' },
      { id: 'PTDN-JP008', name: 'ユベル－Ｄａｓ Ｅｘｔｒｅｍｅｒ Ｔｒａｕｒｉｇ Ｄｒａｃｈｅｎ' },
      { id: 'PTDN-JP016', name: 'ダーク・ホルス・ドラゴン' },
      { id: 'PTDN-JP043', name: 'Ｅ・ＨＥＲＯ ストーム・ネオス' },
      { id: 'PTDN-JP044', name: 'レインボー・ネオス' },
      { id: 'LODT-JP001', name: 'オネスト' },
      { id: 'LODT-JP017', name: 'アルカナフォースＥＸ－ＴＨＥ ＤＡＲＫ ＲＵＬＥＲ' },
      { id: 'LODT-JP026', name: '裁きの龍' },
      { id: 'LODT-JP042', name: 'Ｄｒａｇｏｏｎ Ｄ－ＥＮＤ' },
      { id: 'LODT-JP043', name: '古代の機械究極巨人' },
      { id: 'SD09-JPS01', name: '超伝導恐獣' },
      { id: 'SD10-JPS01', name: '古代の機械巨竜' },
      { id: 'SD11-JPS01', name: '天空勇士ネオパーシアス' },
      { id: 'BPCT-JP005', name: 'F・G・D' },
      { id: 'DPC1-JP001', name: 'ユベル' },
    ],
  },
  {
    period: '第6期',
    cards: [
      { id: 'TDGS-JP039', name: 'ニトロ・ウォリアー' },
      { id: 'TDGS-JP040', name: 'スターダスト・ドラゴン' },
      { id: 'TDGS-JP041', name: 'レッド・デーモンズ・ドラゴン' },
      { id: 'TDGS-JP042', name: 'ゴヨウ・ガーディアン' },
      { id: 'TDGS-JP044', name: 'メンタルスフィア・デーモン' },
      { id: 'CSOC-JP038', name: 'ターボ・ウォリアー' },
      { id: 'CSOC-JP039', name: 'ブラック・ローズ・ドラゴン' },
      { id: 'CSOC-JP043', name: 'デスカイザー・ドラゴン' },
      { id: 'CSOC-JP044', name: '蘇りし魔王 ハ・デス' },
      { id: 'CSOC-JP065', name: '緊急同調' },
      { id: 'CRMS-JP004', name: 'レッド・デーモンズ・ドラゴン／バスター' },
      { id: 'CRMS-JP019', name: 'デスカイザー・ドラゴン／バスター' },
      { id: 'CRMS-JP020', name: 'ハイパーサイコガンナー／バスター' },
      { id: 'CRMS-JP021', name: 'アーカナイト・マジシャン／バスター' },
      { id: 'CRMS-JP041', name: 'ＢＦ－アーマード・ウィング' },
      { id: 'RGBT-JP019', name: '地縛神 Ａｓｌｌａ ｐｉｓｃｕ' },
      { id: 'RGBT-JP020', name: '地縛神 Ｃｃａｐａｃ Ａｐｕ' },
      { id: 'RGBT-JP040', name: 'エクスプロード・ウィング・ドラゴン' },
      { id: 'RGBT-JP042', name: 'パワー・ツール・ドラゴン' },
      { id: 'RGBT-JP043', name: 'トライデント・ドラギオン' },
      { id: 'ANPR-JP016', name: '地縛神 Ｃｕｓｉｌｌｕ' },
      { id: 'ANPR-JP017', name: '地縛神 Ｃｈａｃｕ Ｃｈａｌｌｈｕａ' },
      { id: 'ANPR-JP040', name: 'エンシェント・フェアリー・ドラゴン' },
      { id: 'ANPR-JP042', name: 'アンデット・スカル・デーモン' },
      { id: 'ANPR-JP044', name: 'XX-セイバー ガトムズ' },
      { id: 'SOVR-JP024', name: '地縛神 Ｃｃａｒａｙｈｕａ' },
      { id: 'SOVR-JP025', name: '地縛神 Ｕｒｕ' },
      { id: 'SOVR-JP026', name: '地縛神 Ｗｉｒａｑｏｃｈａ Ｒａｓｃａ' },
      { id: 'SOVR-JP040', name: 'セイヴァー・スター・ドラゴン' },
      { id: 'SOVR-JP041', name: 'ＢＦ－孤高のシルバー・ウィンド' },
      { id: 'ABPF-JP040', name: 'セイヴァー・デモン・ドラゴン' },
      { id: 'ABPF-JP041', name: 'ドリル・ウォリアー' },
      { id: 'ABPF-JP042', name: '太陽龍インティ' },
      { id: 'ABPF-JP043', name: '月影龍クイラ' },
      { id: 'ABPF-JP044', name: 'ＸＸ－セイバー ヒュンレイ' },
      { id: 'TSHD-JP040', name: 'ブラックフェザー・ドラゴン' },
      { id: 'TSHD-JP041', name: 'デーモン・カオス・キング' },
      { id: 'TSHD-JP042', name: 'インフェルニティ・デス・ドラゴン' },
      { id: 'TSHD-JP043', name: 'スプレンディッド・ローズ' },
      { id: 'TSHD-JP044', name: 'カオス・ゴッデス－混沌の女神－' },
    ],
  },
  {
    period: '第7期',
    cards: [
      { id: 'DREV-JP038', name: '波動竜騎士 ドラゴエクィテス' },
      { id: 'DREV-JP041', name: 'ボルテック・バイコーン' },
      { id: 'DREV-JP042', name: 'ライトニング・トライコーン' },
      { id: 'DREV-JP043', name: 'スクラップ・ドラゴン' },
      { id: 'DREV-JP044', name: 'エレキマイラ' },
      { id: 'STBL-JP038', name: '覇魔導士アーカナイト・マジシャン' },
      { id: 'STBL-JP040', name: 'シューティング・スター・ドラゴン' },
      { id: 'STBL-JP042', name: 'スカーレッド・ノヴァ・ドラゴン' },
      { id: 'STBL-JP043', name: 'カラクリ将軍 無零' },
      { id: 'STBL-JP044', name: 'スクラップ・ツイン・ドラゴン' },
      { id: 'STOR-JP038', name: '極神皇トール' },
      { id: 'STOR-JP039', name: '極神皇ロキ' },
      { id: 'STOR-JP040', name: '極神聖帝オーディン' },
      { id: 'STOR-JP042', name: 'カラクリ大将軍 無零怒' },
      { id: 'STOR-JP043', name: 'アトミック・スクラップ・ドラゴン' },
      { id: 'EXVC-JP037', name: 'ジャンク・バーサーカー' },
      { id: 'EXVC-JP038', name: 'ライフ・ストリーム・ドラゴン' },
      { id: 'EXVC-JP042', name: 'TG ブレード・ガンナー' },
      { id: 'EXVC-JP043', name: 'TG ハルバード・キャノン' },
      { id: 'EXVC-JP044', name: 'メンタルオーバー・デーモン' },
      { id: 'GENF-JP039', name: 'No.１７ リバイス・ドラゴン' },
      { id: 'GENF-JP040', name: '潜航母艦 エアロ・シャーク' },
      { id: 'GENF-JP041', name: 'No.３４ 電算機獣 テラ・バイト' },
      { id: 'GENF-JP043', name: '虚空海竜リヴァイエール' },
      { id: 'GENF-JP044', name: '始祖の守護者ティラス' },
      { id: 'PHSW-JP011', name: '銀河眼の光子竜' },
      { id: 'PHSW-JP040', name: 'No.１０ 白騎士イルミネーター' },
      { id: 'PHSW-JP041', name: 'Ｎｏ.２０ 蟻岩土ブリリアント' },
      { id: 'PHSW-JP043', name: 'エヴォルカイザー・ラギア' },
      { id: 'PHSW-JP044', name: 'サンダーエンド・ドラゴン' },
      { id: 'ORCS-JP040', name: 'CNo.39 希望皇ホープレイ' },
      { id: 'ORCS-JP042', name: 'No.１２ 機甲忍者 クリムゾン・シャドー' },
      { id: 'ORCS-JP043', name: 'No.96 ブラック・ミスト' },
      { id: 'ORCS-JP045', name: 'エヴォルカイザー・ソルデ' },
      { id: 'ORCS-JP046', name: '甲虫装機 エクサビートル' },
      { id: 'GAOV-JP041', name: '超銀河眼の光子龍' },
      { id: 'GAOV-JP042', name: 'No.３２ 海咬龍シャーク・ドレイク' },
      { id: 'GAOV-JP045', name: 'No.２５ 重装光学撮影機フォーカス・フォース' },
      { id: 'GAOV-JP048', name: '聖刻神龍-エネアード' },
      { id: 'GAOV-JP050', name: '甲虫装機 エクサスタッグ' },
    ],
  },
  {
    period: '第8期',
    cards: [
      { id: 'REDU-JP041', name: 'H-C エクスカリバー' },
      { id: 'REDU-JP042', name: '先史遺産クリスタル・エイリアン' },
      { id: 'REDU-JP043', name: 'Ｎｏ.３３ 先史遺産－超兵器マシュ＝マック' },
      { id: 'REDU-JP044', name: '超次元ロボ ギャラクシー・デストロイヤー' },
      { id: 'REDU-JP045', name: '魔導法皇 ハイロン' },
      { id: 'ABYR-JP039', name: 'CNo.３９ 海咬龍シャーク・ドレイク・バイス' },
      { id: 'ABYR-JP040', name: '隻眼のスキルゲイナー' },
      { id: 'ABYR-JP044', name: 'Ｎｏ.９ 天蓋星ダイソン・スフィア' },
      { id: 'ABYR-JP045', name: 'Ｎｏ.８ 紋章王ゲノム・ヘリター' },
      { id: 'ABYR-JP046', name: '水精鱗－ガイオアビス' },
      { id: 'CBLZ-JP020', name: 'オービタル ７' },
      { id: 'CBLZ-JP045', name: 'Ｎｏ.９２ 偽骸神龍 Ｈｅａｒｔ－ｅａｒｔＨ Ｄｒａｇｏｎ' },
      { id: 'CBLZ-JP046', name: 'Ｎｏ.５３ 偽骸神 Ｈｅａｒｔ－ｅａｒtＨ' },
      { id: 'CBLZ-JP047', name: 'ＺＷ－獣王獅子武装' },
      { id: 'CBLZ-JP048', name: '魁炎星王－ソウコ' },
      { id: 'LTGY-JP044', name: 'Ｎｏ.１０７ 銀河眼の時空竜' },
      { id: 'LTGY-JP051', name: 'Ｎｏ.１０５ ＢＫ 流星のセスタス' },
      { id: 'LTGY-JP052', name: 'ＣＮｏ.１０５ ＢＫ 彗星のカエストス' },
      { id: 'LTGY-JP053', name: '幻獣機 ドラゴサック' },
      { id: 'LTGY-JP060', name: 'ＲＵＭ－バリアンズ・フォース' },
      { id: 'JOTL-JP047', name: '星態龍' },
      { id: 'JOTL-JP048', name: 'ＣＮｏ.３９ 希望皇ホープレイ・ヴィクトリー' },
      { id: 'JOTL-JP056', name: 'ＣＮｏ.１０４ 仮面魔踏士アンブラル' },
      { id: 'JOTL-JP057', name: '武神帝－スサノヲ' },
      { id: 'JOTL-JP059', name: 'ＲＵＭ－ヌメロン・フォース' },
      { id: 'SHSP-JP046', name: 'ＣＮｏ.９６ ブラック・ストーム' },
      { id: 'SHSP-JP050', name: 'Ｎｏ.４６ 神影龍ドラッグルーオン' },
      { id: 'SHSP-JP052', name: 'ゴーストリック・アルカード' },
      { id: 'SHSP-JP053', name: '武神帝－カグツチ' },
      { id: 'SHSP-JP056', name: '神竜騎士フェルグラント' },
      { id: 'LVAL-JP046', name: 'ＣＮｏ.１０１ Ｓ・Ｈ・Ｄａｒｋ Ｋｎｉｇｈｔ' },
      { id: 'LVAL-JP047', name: 'Ｎｏ.１０１ Ｓ・Ｈ・Ａｒｋ Ｋｎｉｇｈｔ' },
      { id: 'LVAL-JP048', name: 'Ｎｏ.３９ 希望皇ホープ・ルーツ' },
      { id: 'LVAL-JP054', name: '武神帝－ツクヨミ' },
      { id: 'LVAL-JP059', name: 'ＲＵＭ－アストラル・フォース' },
      { id: 'PRIO-JP040', name: 'Ｎｏ.６２ 銀河眼の光子竜皇' },
      { id: 'PRIO-JP041', name: 'ＣＮｏ.１０７ 超銀河眼の時空龍' },
      { id: 'PRIO-JP044', name: 'ＣＮｏ.１０２ 光堕天使ノーブル・デーモン' },
      { id: 'PRIO-JP049', name: 'アーティファクト－デュランダル' },
      { id: 'PRIO-JP052', name: '武神姫－アマテラス' },
      { id: 'PRIO-JP058', name: 'ＲＵＭ－七皇の剣' },
    ],
  },
  {
    period: '第9期',
    cards: [
      { id: 'DUEA-JP004', name: 'オッドアイズ・ペンデュラム・ドラゴン' },
      { id: 'DUEA-JP049', name: 'エルシャドール・ネフィリム' },
      { id: 'DUEA-JP050', name: '竜姫神サフィラ' },
      { id: 'DUEA-JP051', name: '輝竜星-ショウフク' },
      { id: 'DUEA-JP053', name: '星輝士 デルタテロス' },
      { id: 'DUEA-JP087', name: 'No.８６ H-C ロンゴミアント' },
      { id: 'NECH-JP046', name: 'デストーイ・シザー・ベアー' },
      { id: 'NECH-JP049', name: 'エルシャドール・シェキナーガ' },
      { id: 'NECH-JP051', name: '邪竜星-ガイザー' },
      { id: 'NECH-JP053', name: 'ダーク・リベリオン・エクシーズ・ドラゴン' },
      { id: 'NECH-JP054', name: '星輝士 トライヴェール' },
      { id: 'NECH-JP081', name: 'FNo.０ 未来皇ホープ' },
      { id: 'SECE-JP019', name: 'インフェルノイ・ネヘモス' },
      { id: 'SECE-JP044', name: 'グングニールの影霊衣' },
      { id: 'SECE-JP045', name: 'ルーンアイズ・ペンデュラム・ドラゴン' },
      { id: 'SECE-JP048', name: '超重荒神スサノ-O' },
      { id: 'SECE-JP049', name: 'メタファイズ・ホルス・ドラゴン' },
      { id: 'SECE-JP051', name: '星輝士 セイクリッド・ダイヤ' },
      { id: 'CROS-JP038', name: 'sophiaの影霊衣' },
      { id: 'CROS-JP043', name: 'デストーイ・マッド・キマイラ' },
      { id: 'CROS-JP045', name: '聖霊獣騎 ガイアペライオ' },
      { id: 'CROS-JP046', name: 'クリアウィング・シンクロ・ドラゴン' },
      { id: 'CROS-JP050', name: '星守の騎士 プトレマイオス' },
      { id: 'CROS-JP090', name: 'サイバー・ドラゴン・インフィニティ' },
      { id: 'CORE-JP048', name: '悪魔竜ブラック・デーモンズ・ドラゴン' },
      { id: 'CORE-JP049', name: 'インフェルノイド・ティエラ' },
      { id: 'CORE-JP050', name: '爆竜剣士 イグニスターP' },
      { id: 'CORE-JP051', name: '覇王黒竜オッドアイズ・リベリオン・ドラゴン' },
      { id: 'CORE-JP052', name: 'DDD狙撃王テル' },
      { id: 'CORE-JP054', name: '真紅眼の鋼炎竜' },
      { id: 'DOCS-JP042', name: '超戦士カオス・ソルジャー' },
      { id: 'DOCS-JP045', name: 'オッドアイズ・ボルテックス・ドラゴン' },
      { id: 'DOCS-JP046', name: 'レッド・デーモンズ・ドラゴン・スカーライト' },
      { id: 'DOCS-JP047', name: 'A BF-驟雨のライキリ' },
      { id: 'DOCS-JP050', name: 'DDD双暁王カリ・ユガ' },
      { id: 'DOCS-JP052', name: '昇竜剣士マジェスターP' },
      { id: 'BOSH-JP018', name: '破壊剣の使い手-バスター・ブレイダー' },
      { id: 'BOSH-JP043', name: 'オッドアイズ・グラビティ・ドラゴン' },
      { id: 'BOSH-JP045', name: '竜破壊の剣士-バスター・ブレイダー' },
      { id: 'BOSH-JP046', name: '剛竜剣士ダイナスターP' },
      { id: 'BOSH-JP047', name: '覚醒の魔道剣士' },
      { id: 'BOSH-JP054', name: '戦神-不知火' },
      { id: 'SHVI-JP018', name: '白き霊龍' },
      { id: 'SHVI-JP044', name: '虚竜魔王アモルファクターP' },
      { id: 'SHVI-JP048', name: '月光舞獅子姫' },
      { id: 'SHVI-JP049', name: 'クリスタルウィング・シンクロ・ドラゴン' },
      { id: 'SHVI-JP051', name: 'A BF-涙雨のチドリ' },
      { id: 'SHVI-JP052', name: '青眼の精霊龍' },
      { id: 'TDIL-JP020', name: '真竜剣士マスターP' },
      { id: 'TDIL-JP046', name: '涅槃の超魔導剣士' },
      { id: 'TDIL-JP049', name: 'A BF- 神立のオニマル' },
      { id: 'TDIL-JP050', name: 'レッド・デーモンズ・ドラゴン・タイラント' },
      { id: 'TDIL-JP051', name: '瑚之龍' },
      { id: 'TDIL-JP052', name: '虚空の黒魔導士' },
      { id: 'INOV-JP037', name: '古聖戴サウラヴィス' },
      { id: 'INOV-JP038', name: 'スターヴ・ヴェノム・フュージョン・ドラゴン' },
      { id: 'INOV-JP041', name: '流星竜メテオ・ブラック・ドラゴン' },
      { id: 'INOV-JP046', name: '水晶機巧-フェニキシオン' },
      { id: 'INOV-JP049', name: 'ダーク・レクイエム・エクシーズ・ドラゴン' },
      { id: 'INOV-JP051', name: '煉獄の騎士 ヴァトライムス' },
      { id: 'RATE-JP039', name: 'ブレイブアイズ・ペンデュラム・ドラゴン' },
      { id: 'RATE-JP041', name: '古代の機械混沌巨人' },
      { id: 'RATE-JP046', name: '水晶機巧-グリオンガンド' },
      { id: 'RATE-JP048', name: '覇王烈竜オッドアイズ・レイジング・ドラゴン' },
      { id: 'RATE-JP049', name: '超銀河眼の光波龍' },
      { id: 'RATE-JP053', name: '十二獣ドランシア' },
      { id: 'MACR-JP001', name: 'EMスカイ・マジシャン' },
      { id: 'MACR-JP025', name: '真竜騎兵ダースメタトロン' },
      { id: 'MACR-JP030', name: '智天の神星龍' },
      { id: 'MACR-JP039', name: '覇王龍ズァーク' },
      { id: 'MACR-JP046', name: '真竜皇V.F.D.' },
      { id: 'MACR-JP052', name: '超越融合' },
      { id: 'TRC1-JP002', name: '死者蘇生' },
      { id: 'TRC1-JP004', name: '超融合' },
      { id: 'TRC1-JP006', name: 'スターライト・ロード' },
      { id: 'TRC1-JP008', name: 'RUM-アストラル・フォース' },
    ],
  },
  {
    period: '第10期',
    cards: [
      { id: 'COTD-JP028', name: '戒めの龍' },
      { id: 'COTD-JP043', name: 'ファイアウォール・ドラゴン' },
      { id: 'COTD-JP044', name: 'トリックスター・ホーリーエンジェル' },
      { id: 'COTD-JP045', name: '剛鬼ザ・グレート・オーガ' },
      { id: 'COTD-JP046', name: 'トポロジック・ボマー・ドラゴン' },
      { id: 'COTD-JP050', name: '聖杯戦士ニンギルス' },
      { id: 'CIBR-JP027', name: 'メタファイズ・エクゼキューター' },
      { id: 'CIBR-JP042', name: 'ヴァレルロード・ドラゴン' },
      { id: 'CIBR-JP044', name: 'トリックスター・スイートデビル' },
      { id: 'CIBR-JP045', name: '剛鬼サンダー・オーガ' },
      { id: 'CIBR-JP047', name: 'オルターガイスト・プライムバンシー' },
      { id: 'CIBR-JP050', name: 'エクスクローラー・クオリアーク' },
      { id: 'EXFO-JP027', name: '魔導獣 マスターケルベロス' },
      { id: 'EXFO-JP038', name: 'エクスコード・トーカー' },
      { id: 'EXFO-JP044', name: 'スリーバーストショット・ドラゴン' },
      { id: 'EXFO-JP045', name: 'ティンダングル・アキュート・ケルベロス' },
      { id: 'EXFO-JP047', name: '星痕の機界騎士' },
      { id: 'EXFO-JP048', name: '鎖龍蛇-スカルデット' },
      { id: 'FLOD-JP025', name: 'エレメントセイバー・ウィラード' },
      { id: 'FLOD-JP032', name: '鉄騎龍ティアマトン' },
      { id: 'FLOD-JP036', name: 'トポロジック・トゥリスバエナ' },
      { id: 'FLOD-JP038', name: 'トリックスター・ベラマドンナ' },
      { id: 'FLOD-JP041', name: '剛鬼ザ・マスター・オーガ' },
      { id: 'FLOD-JP048', name: 'トロイメア・グリフォン' },
      { id: 'CYHO-JP021', name: '魔晶龍ジルドラス' },
      { id: 'CYHO-JP026', name: 'サイバース・マジシャン' },
      { id: 'CYHO-JP033', name: 'ドラグニティナイトーアスカロン' },
      { id: 'CYHO-JP034', name: 'ヴァレルソード・ドラゴン' },
      { id: 'CYHO-JP044', name: 'アークロード・パラディオン' },
      { id: 'CYHO-JP046', name: 'サイバー・ドラゴン・ズィーガー' },
      { id: 'SOFU-JP025', name: '混源龍レヴィオニア' },
      { id: 'SOFU-JP034', name: 'サイバース・クロック・ドラゴン' },
      { id: 'SOFU-JP037', name: '雷神龍－サンダー・ドラゴン' },
      { id: 'SOFU-JP042', name: '銀河眼の煌星竜' },
      { id: 'SOFU-JP045', name: 'オルフェゴール・オーケストリオン' },
      { id: 'SOFU-JP047', name: '空牙団の大義 フォルゴ' },
      { id: 'SAST-JP020', name: '幻創龍ファンタズメイ' },
      { id: 'SAST-JP036', name: 'E・HERO コスモ・ネオス' },
      { id: 'SAST-JP037', name: 'ヴァレルロード・S・ドラゴン' },
      { id: 'SAST-JP038', name: 'サイバース・クアンタム・ドラゴン' },
      { id: 'SAST-JP050', name: 'TG トライデント・ランチャー' },
      { id: 'SAST-JP054', name: '麗神－不知火' },
      { id: 'DANE-JP020', name: '妖醒龍ラルバウール' },
      { id: 'DANE-JP036', name: 'ファイアウォール・X・ドラゴン' },
      { id: 'DANE-JP038', name: '宵星の機神ディンギルス' },
      { id: 'DANE-JP047', name: '双穹の騎士アストラム' },
      { id: 'DANE-JP050', name: '揚陸群艦アンブロエール' },
      { id: 'DANE-JP051', name: 'サイバネット・マイニング' },
      { id: 'RIRA-JP011', name: '魔妖仙獣 独眼群主' },
      { id: 'RIRA-JP021', name: '烈風の覇者シムルグ' },
      { id: 'RIRA-JP029', name: '機巧蛇－叢雲遠呂智' },
      { id: 'RIRA-JP039', name: 'ヴァレルロード・Ｘ・ドラゴン' },
      { id: 'RIRA-JP047', name: 'リンクメイル・デーモン' },
      { id: 'RIRA-JP048', name: '召命の神弓－アポロウーサ' },
      { id: 'CHIM-JP023', name: '機巧嘴－八咫御先' },
      { id: 'CHIM-JP033', name: '剣闘獣ドミティアノス' },
      { id: 'CHIM-JP035', name: '天威の龍鬼神' },
      { id: 'CHIM-JP037', name: 'ファイアウォール・ドラゴン・ダークフルード' },
      { id: 'CHIM-JP039', name: '転生炎獣パイロ・フェニックス' },
      { id: 'CHIM-JP045', name: '破械雙王神ライゴウ' },
      { id: 'IGAS-JP011', name: '戦華の徳－劉玄' },
      { id: 'IGAS-JP024', name: '機巧蹄－天迦久御雷' },
      { id: 'IGAS-JP040', name: 'メガリス・アラトロン' },
      { id: 'IGAS-JP043', name: 'カラクリ大権現 無零武' },
      { id: 'IGAS-JP044', name: 'ライトドラゴン＠イグニスター' },
      { id: 'IGAS-JP045', name: 'ダークナイト＠イグニスター' },
      { id: 'ETCO-JP031', name: '機巧狐－宇迦之御魂稲荷' },
      { id: 'ETCO-JP041', name: 'ドラゴンメイド・シュトラール' },
      { id: 'ETCO-JP044', name: 'ヴァリアント・シャーク・ランサー' },
      { id: 'ETCO-JP046', name: 'アクセスコード・トーカー' },
      { id: 'ETCO-JP050', name: 'ジ・アライバル・サイバース＠イグニスター' },
      { id: 'ETCO-JP054', name: '海晶乙女グレート・バブル・リーフ' },
      { id: 'RC02-JP006', name: 'ラーの翼神竜-球体形' },
      { id: 'RC02-JP007', name: 'E・HERO オネスティ・ネオス' },
      { id: 'RC02-JP008', name: '幽鬼うさぎ' },
      { id: 'RC02-JP009', name: '灰流うらら' },
      { id: 'RC02-JP010', name: '強欲で貪欲な壺' },
    ],
  },
];
